name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.5.0

    - name: Install Dependencies
      run: npm install

    - name: Build and Package Electron App for macOS
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: npm run dist:mac

  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.5.0

    - name: Install Dependencies
      run: npm install

    - name: Build and Package Electron App for Windows
      run: npm run dist:win

  build-linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.5.0

    - name: Install Dependencies
      run: npm install

    - name: Build and Package Electron App for Linux
      run: npm run dist:linux
